import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
	myMusicContainer: {
		flex: 1,
		width: '100%',
		backgroundColor: '#f5f5f5',
	},
	listRow: {
		flex: 1,
		flexDirection: 'row',
		justifyContent: 'flex-start',
		alignItems: 'center',
		height: 65,
	},
	listTextPlaying: {
		fontSize: 15,
		color: '#000',
		fontWeight: 'bold',
		textAlign: 'left',
		marginLeft: 10,
	},
	songImage: {
		width: 50,
		height: 50,
	},
	listText: {
		fontSize: 15,
		textAlign: 'left',
		color: '#333',
		marginLeft: 10,
	},
	imageContainer: {
		flexDirection: 'row',
		justifyContent: 'center',
		alignItems: 'center',
		width: '20%',
	},
	textContainer: {
		width: '65%',
	},
	moreContainer: {
		flexDirection: 'row',
		justifyContent: 'center',
		alignItems: 'center',
		width: '15%',
	},
	menu: {
		height: 75,
		flex: 1,
		flexDirection: 'row',
		justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: '#ff6666',
	},
	menuOption: {
		height: '100%',
		flex: 1,
		flexDirection: 'row',
		justifyContent: 'center',
		alignItems: 'center',
	},
	editSongContainer: {
		flex: 1,
		flexDirection: 'column',
		justifyContent: 'center',
		alignItems: 'center',
	},
	editSongImageContainer: {
		flex: 6,
		flexDirection: 'column',
		justifyContent: 'center',
		alignItems: 'center',
		width: '100%',
	},
	editSongImage: {
		height: '100%',
		width: '100%',
	},
	songTextContainer: {
		flex: 1,
		flexDirection: 'column',
		justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: '#fafafa',
		width: '100%',
	},
	currentTextTitle: {
		fontSize: 20,
		textAlign: 'center',
		width: '90%',
	},
	currentTextArtist: {
		fontSize: 15,
		textAlign: 'center',
		width: '90%',
	},
	textInputsContainer: {
		flex: 4,
		flexDirection: 'column',
		justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: '#ff6666',
		width: '100%',
	},
	textInputContainer: {
		flexDirection: 'row',
		justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: '#ff6666',
		width: '100%',
	},
	buttonContainer: {
		flexDirection: 'row',
		justifyContent: 'flex-start',
		alignItems: 'center',
	},
	button: {
		color: '#ff6666',
		fontWeight: 'bold',
		fontSize: 17,
	},
	modalView: {
		flex: 1,
		backgroundColor: 'rgba(0,0,0,0.1)',
		justifyContent: 'center',
		alignItems: 'center',
	},
	modalSubview: {
		height: 250,
		width: 250,
		backgroundColor: '#f5f5f5',
		padding: 25,
		flexDirection: 'column',
		justifyContent: 'space-between',
		alignItems: 'flex-start',
	},
	modalInputComponent: {
		flex: 1,
		width: '100%',
		flexDirection: 'column',
		justifyContent: 'center',
		alignItems: 'flex-start',
	},
	modalHeaderText: {
		color: '#000',
		fontSize: 18,
		fontWeight: 'bold',
	},
	modalText: {
		color: '#000',
		fontSize: 13,
		fontWeight: 'bold',
	},
	textInput: {
		width: '100%',
		height: 40,
	},
});
export default styles;
